sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=7b1638da1e236698ba5b292a38a8779c75010f04319d59c1d9b7cb8e404d8f05
