sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=a82ea449b07b6c7cae76e510b80bf3851c3ee06039378518d020c1e936cfea06
